/*
Crea una aplicación GUI en Java que gestione una lista de productos. La interfaz debe contener
los siguientes elementos:
1. Un ComboBox (JComboBox) que permita al usuario seleccionar una categoría de producto
de una lista predefinida (por ejemplo, electrónica, ropa, alimentos, etc.).
2. Un botón "Agregar producto" (JButton) que permita al usuario agregar un nuevo producto
a la lista.
3. Una tabla (JTable) que muestre los productos agregados, con columnas para el nombre del
producto, la categoría y el precio.
Cuando el usuario seleccione una categoría en el ComboBox y haga clic en el botón "Agregar
producto", el programa debe permitir al usuario ingresar el nombre y el precio del producto en
campos de texto separados. Luego, debe agregar el producto a la tabla con la categoría
seleccionada.
Además, la tabla debe ser actualizada automáticamente cada vez que se agrega un nuevo producto.
 */
package act03;

import javax.swing.*;

public class Interfaz extends javax.swing.JFrame {

    
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        datositem = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaprod1 = new javax.swing.JTable();
        item = new javax.swing.JComboBox<>();
        botagregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaprod = new javax.swing.JTable();

        listaprod1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Cantidad"
            }
        ));
        jScrollPane3.setViewportView(listaprod1);

        javax.swing.GroupLayout datositemLayout = new javax.swing.GroupLayout(datositem.getContentPane());
        datositem.getContentPane().setLayout(datositemLayout);
        datositemLayout.setHorizontalGroup(
            datositemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datositemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        datositemLayout.setVerticalGroup(
            datositemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datositemLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        item.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electronica", "Ropa", "Alimentos" }));

        botagregar.setText("Agregar");
        botagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botagregarActionPerformed(evt);
            }
        });

        listaprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Categoria", "Precio", "Cantidad", "Total"
            }
        ));
        jScrollPane1.setViewportView(listaprod);
        if (listaprod.getColumnModel().getColumnCount() > 0) {
            listaprod.getColumnModel().getColumn(1).setHeaderValue("Categoria");
            listaprod.getColumnModel().getColumn(4).setHeaderValue("Total");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botagregar)
                    .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(item, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botagregar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botagregarActionPerformed
        
        JOptionPane.showInputDialog(botagregar, )
        
    }//GEN-LAST:event_botagregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botagregar;
    private javax.swing.JDialog datositem;
    private javax.swing.JComboBox<String> item;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable listaprod;
    private javax.swing.JTable listaprod1;
    // End of variables declaration//GEN-END:variables
}
